# .github/workflows/daily_scrape.yml
name: Daily Scrape & Update

on:
  # 毎朝 6:00 JST → UTC 前日 21:00 にスケジュール実行
  schedule:
    - cron: '0 21 * * *'
  # 手動実行用ボタン
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scrape script
        env:
          GSPREAD_JSON: ${{ secrets.GSPREAD_JSON }}
          SHEET_ID:     ${{ secrets.SHEET_ID }}
          LOGIN_URL: ${{ secrets.LOGIN_URL }}
          LOGIN_USER: ${{ secrets.LOGIN_USER }}
          LOGIN_PASS: ${{ secrets.LOGIN_PASS }}
          LOGIN_SUCCESS_URL: ${{ secrets.LOGIN_SUCCESS_URL }}
          WEB_BASE: ${{ secrets.WEB_BASE }}

        run: |
          python scrape_and_update.py

      - name: Dump secret snippet
        run: |
          echo "----BEGIN PRIVATE_KEY SNIPPET----"
          echo "${{ secrets.GSPREAD_JSON }}" | head -n5
          echo "----END SNIPPET----"
